### ISSUE TITLE
Omni_listproperties does not see complete tokens

### ISSUE THREAD

**Issue by tangjielong** [OmniLayer/omnicore#705] opened 2018-07-25 09:23 UTC
root@SS02:/usr/local/omnicore/src# ./omnicore-cli -rpcport=8332 "omni_listproperties" 
[
  {
    "propertyid": 1,
    "name": "Omni",
    "category": "N/A",
    "subcategory": "N/A",
    "data": "Omni serve as the binding between Bitcoin, smart properties and contracts created on the Omni Layer.",
    "url": "http://www.omnilayer.org",
    "divisible": true
  }, 
  {
    "propertyid": 2,
    "name": "Test Omni",
    "category": "N/A",
    "subcategory": "N/A",
    "data": "Test Omni serve as the binding between Bitcoin, smart properties and contracts created on the Omni Layer.",
    "url": "http://www.omnilayer.org",
    "divisible": true
  }
]

**Comment by dexX7** [comment] 2018-07-26 13:31
Duplicate of #704.

**Closed by dexX7** 2018-07-26 13:31 UTC
