### ISSUE TITLE
CheckProofOfWork() : nBits below minimum work

### ISSUE THREAD

**Issue by marvgmail** [OmniLayer/omnicore#151] opened 2015-07-28 19:44 UTC
Trying to initialize the db on OSX 10.10.4:

>...
2015-07-27 21:43:39 UpdateTip: new best=0000000000000000d85600ae98b2c9f9087b476730db6e895837ca9b197470e6  height=294005  log2_work=77.730053  tx=36163410  date=2014-04-03 18:21:19 progress=0.202320  cache=85660
2015-07-27 21:43:39 UpdateTip: new best=0000000000000000475a1ab75412756f73d663de34a58541d49bfc9740fb4302  height=294006  log2_work=77.730177  tx=36163762  date=2014-04-03 18:29:32 progress=0.202322  cache=85946
2015-07-27 21:43:40 UpdateTip: new best=0000000000000000786d3578f61358b0d27b694500d1c72154bdf712d4cbff6c  height=294007  log2_work=77.7303  tx=36164349  date=2014-04-03 18:41:28 progress=0.202325  cache=86582
2015-07-27 21:43:40 ERROR: CheckProofOfWork() : nBits below minimum work
2015-07-27 21:43:40 ERROR: ReadBlockFromDisk : Errors in block header
2015-07-27 21:43:40 *** Failed to read block
2015-07-27 21:48:00 UPnP Port Mapping successful.

**Comment by dexX7** [comment] 2015-07-28 20:40
At first I thought this is a duplicate of https://github.com/OmniLayer/omnicore/issues/115#issuecomment-118840092, but I tend to believe this is caused by file/database corruption.

Did the synchronization continue after this point?

**Comment by marvgmail** [comment] 2015-07-28 21:45
@dexX7 It stopped.

**Comment by zathras-crypto** [comment] 2015-07-29 01:33
@marvgmail as a first step it might be useful to try syncing up on testnet as this will be a lot quicker and require a lot less bandwidth (see the MetaDEx guide here https://github.com/OmniLayer/omnicore/blob/omnicore-0.0.10/doc/metadextestingguide.md, please let me know if the OSX syntax is correct).

Also at the meeting this morning it was discussed between Sean & Craig that OSX has a default 256 open file limitation?  This seems bizarre to me but if that's accurate then I can definitely see running out of file handles causing IO problems, perhaps increasing that value might help.

The issue is in syncing the blockchain which isn't something our Omni code intrudes on but it's still obviously something we need to get to the bottom of.

I think you also mentioned deleting the bitcoin data directory - are you sure Omni was fully stopped at this point?  Without wanting to state the obvious, wiping the bitcoin data directory while Omni Core was still running would likely result in similar log entries (note clicking the red cross in the corner only hides the window, it still runs in the tray/dock - use File > Exit).

**Comment by dexX7** [comment] 2015-07-29 14:31
Running out of file descriptors should be visible as such, with a clear error message. This is at least my experience with the address index branch, which initially had a file descriptor leak.

I suggest to open an issue [upstream](https://github.com/bitcoin/bitcoin/issues). The underlying code base we currently use is Bitcoin Core 0.10.2. As @zathras-crypto noted, at this point (synchronizing, before Exodus), the Omni componente is basically inactive.

**Comment by dexX7** [comment] 2015-08-10 18:35
@marvgmail: is there an update on this issue?

**Comment by dexX7** [comment] 2015-08-22 10:34
Given that there was no feedback from the original author for 25 days, and it couldn't be confirmed that this issue is indeed related to Omni Core, I'm going to close the issue for now, because I don't see how we can make progress on this.

Further input on this would be very welcomed at any time, and if there are any new insights, or observations, the issue should be reopened.

**Closed by dexX7** 2015-08-22 10:34 UTC
Labels: bug

**Comment by dexX7** [comment] 2015-08-26 23:29
To finally provide an update:

Appearingly an anti virus product, ClamXav for Mac OS X, accessed the LevelDB files during the synchronization, which caused corruptions. There were [reports](https://www.google.de/search?q=bitcoin+virus+signature) of virus signatures embedded in the mainnet chain, and it looks like they were identified by ClamXav.

FWIW: I'm using https://www.malwarebytes.org/, and they even [accept BTC](https://blog.malwarebytes.org/news/2014/02/malwarebytes-now-accepts-bitcoins/). :) .. just not at the very moment, because Coinbase [has some issues](https://www.reddit.com/r/Bitcoin/comments/3igx77/wikimedia_quietly_removes_bitcoin_donations_from/cugcz35).

**Comment by dexX7** [comment] 2015-09-06 11:09
@marv-engine @marvgmail: is there any chance you can provide more details about what ClamXav did, i.e. how the findings were classified, or by which files it was caused?
