### ISSUE TITLE
CI still failing

### ISSUE THREAD

**Issue by zathras-crypto** [OmniLayer/omnicore#330] opened 2016-01-04 20:08 UTC
I wanted to look into why Jenkins CI still seems to be failing, and found that OmniChest has not been displaying reserved balances properly.  I've now fixed this fault, but the latest still seems to have failed (seemingly due to a blockheight mismatch).  Any thoughts?

**Comment by dexX7** [comment] 2016-01-04 20:34
Yeah, I guess it's caused by the difference between CI server height and Chest height. Do you still maintain the 1 minute update frequency?

CC: @msgilligan

**Comment by zathras-crypto** [comment] 2016-01-04 20:45
Hmm, OK - maybe I should revisit that then...

FYI I did switch over to using blocknotify in the early days of Chest v6 development, but what I found was that when two blocks came in quick succession then two Chest engine runs would be kicked off at the same time which essentially shredded the temp tables (which were then pushed to the prod tables making a mess of everything).  I blocked this behaviour, but then found the data from the second block would not be updated until yet another block came in to trigger another update.

In the end while working on pending transactions I found blocknotify wasn't a good fit anyway (as if there was a long time between blocks there would be a long time between adding pending transactions to the DB) so I fell back to the original model of running on a timer, but if that's hurting our CI then I'll revisit and see if I can be a bit more creative about how I do updates (perhaps I'll have to implement some form of queueing).

I need to finalize my work on pending transactions anyway, so time to put my thinking cap on :)

**Comment by dexX7** [comment] 2016-01-04 20:47
There should be two new jobs processing now on the CI server. Let's see how it turns out.

> Hmm, OK - maybe I should revisit that then...

Well, I'm not sure if it's worth the effort. If it's low hanging, I'd say go for it, if not, then it would probably be better to push alternatives, such as reviving the API connector idea?

**Comment by zathras-crypto** [comment] 2016-01-04 20:51
API connector is my "end game" for Chest development and a lot of the core work is already complete for that in 'Chest v6 - I guess I was a little worried about the amount of time I was spending on the API connector stuff but I'd love to revisit it and get it finished off :)

**Comment by dexX7** [comment] 2016-01-04 20:58
It's of course pretty heavy, and if there are alternatives, the better. :)

When considering the greater picture of Omni Core, I'd like to move towards better handling of unconfirmed transactions first (e.g. by getting rid of the pending transaction objects and parsing new unconfirmed transactions right after sending, or maybe even when they hit the mempool). UI support for the traditional DEx was asked for during the last meeting, so this is also on the list. Afterwards we're probably ready to release 10.1.

I'm very open to what happens later. We could tackle the API connector or work towards state snapshots (and full support for unconfirmed state), or maybe start something new, such as the things Craig suggested, BTC crowdsales, atomic swaps etc.

**Comment by zathras-crypto** [comment] 2016-01-04 21:03
Just as a quick FYI, I've got a good chunk of the DEx UI work done, I've been "saving up" the rest for the flight back to Aus as it's a good block of work I can do without a network connection - so expect a push when I get back home :)

Re unconfirmed transactions, depending on the compute required to parse them do we risk node DDOS from a flood of spam Omni transactions or do you think the existing ban code on the Bitcoin side will protect us?

**Comment by dexX7** [comment] 2016-01-04 22:08
Oh, when do you fly? I wish you all the best, haha. :)

> Re unconfirmed transactions, depending on the compute required to parse them do we risk node DDOS from a flood of spam Omni transactions or do you think the existing ban code on the Bitcoin side will protect us?

I haven't thought this through at this point. If we really tap the mempool directly, then I'd probably start to test with just looking for a marker. If there is one, then I'd store the transaction hash as candidate, which is then used as replacement for the pending transaction objects.

I could also imagine to keep a list of Omni transactions and their confirmation state to move away from iterating over wallet transactions, basically extending the idea of a cache, but started on a lower level.

As long as we don't parse the whole mempool over and over, only because the mempool state changes, I'm positive there won't be an impact.

What I'm not sure about is how to handle the class C activation switch-over, because unconfirmed transactions don't have a related block height.

**Comment by dexX7** [comment] 2016-01-05 12:04
The mainnet consensus tests have passed.

Feel free to leave this open, if you'd like to keep track of the issue in relation to Chest, otherwise let's close it. :)

**Comment by zathras-crypto** [comment] 2016-01-05 13:53
> Oh, when do you fly? I wish you all the best, haha. :)

Hehe thanks mate, about 48 hours from now for the first leg (about 10 hours) then hanging around the airport for about 6 hours, then the second leg (about 13 hours)...  Can't say I'm looking forward to it *at all* but the things we do to visit our loved ones hey :)

> As long as we don't parse the whole mempool over and over, only because the mempool state changes, I'm positive there won't be an impact.

Yeah as long as we only parse each transaction once we might be OK - I'm just conscious of the notion of going and grabbing inputs over and over if there are say 20,000 unconfirmed transactions but I haven't really thought much about it. 

> What I'm not sure about is how to handle the class C activation switch-over, because unconfirmed transactions don't have a related block height.

Class C will be live in a couple of weeks, so I'd imagine this becomes a non-issue from then on, as all unconfirmed transactions there-after would have to be mined after the activation height.

> The mainnet consensus tests have passed.  Feel free to leave this open, if you'd like to keep track of the issue in relation to Chest, otherwise let's close it. :)

I'm trying to start tracking Chest issues via GitHub - I've already closed https://github.com/zathras-crypto/omnichest.info/issues/2 so this one can be closed too...

**Comment by dexX7** [comment] 2016-01-05 17:29
> 23 hours on a plane

Oh well... :)

> Class C will be live in a couple of weeks, so I'd imagine this becomes a non-issue from then on, as all unconfirmed transactions there-after would have to be mined after the activation height.

Very, very good point!

**Closed** 2016-01-05 17:28 UTC
Labels: ci and tests
