### ISSUE TITLE
Bug: getsto_MP / omni_getsto  <hash> * doesn't work

### ISSUE THREAD

**Issue by achamely** [OmniLayer/omnicore#212] opened 2015-08-31 20:24 UTC
Calling getsto_MP/omni_getsto  works for the individual hash/txid  but when trying to get the list of all outputs omnicore is not able to recognize the *  for all addresses:

getsto_MP 0937f162eda99e5aeeab550b26ea7cdd1322a3281fe1721b6ae9c8eb0eab374d
{  "error": null,  "id": null,  "result": {   "amount": "1.00000000", ...... } }

getsto_MP 0937f162eda99e5aeeab550b26ea7cdd1322a3281fe1721b6ae9c8eb0eab374d *
Error in getsto_MP RPC call: {u'message': u'Invalid address', u'code': -5}

getsto_MP 0937f162eda99e5aeeab550b26ea7cdd1322a3281fe1721b6ae9c8eb0eab374d "*"
Error in getsto_MP RPC call: {u'message': u'Invalid address', u'code': -5}

omni_getsto 0937f162eda99e5aeeab550b26ea7cdd1322a3281fe1721b6ae9c8eb0eab374d *
Error in omni_getsto RPC call: {u'message': u'Invalid address', u'code': -5}

This is used by omniEngine when parsing/updating its database balances.  
@zathras-crypto or @dexX7 i'm hoping this is a simple bug to patch?

This is running compiled tip to 0b6ff8818983a06146bc75d620755ba831ee04d3

**Comment by dexX7** [comment] 2015-08-31 21:22
Thanks @achamely!

I can confirm this is an issue. I won't be able to push the fix immediately, but it's probably resolved within the next 24 hours.

@zathras-crypto: it likely affects all RPCs with "address or wildcard/empty" input, which already use the `ParseX()` functions, and we could add something like `ParseAddressOrWildcard()`:

- [src/omnicore/rpcvalues.cpp#L14-L21](https://github.com/OmniLayer/omnicore/blob/58f5868b36f2de3a47c8638cdd22c88c5adc26dd/src/omnicore/rpcvalues.cpp#L14-L21)
- [src/omnicore/rpc.cpp#L1496](https://github.com/OmniLayer/omnicore/blob/c7f27da1bbba2d30d8c80bb8dadab0e0e5549b6b/src/omnicore/rpc.cpp#L1496)

We might also add `ParseAddressOrEmpty()` to simplify:

- [src/omnicore/rpc.cpp#L350-L351](https://github.com/OmniLayer/omnicore/blob/c7f27da1bbba2d30d8c80bb8dadab0e0e5549b6b/src/omnicore/rpc.cpp#L350-L351)

```c++
std::string ParseAddressOrEmpty(const json_spirit::Value& value)
{
    if (value.get_str().empty()) {
        return "";
    }
    return ParseAddress(value);
}

std::string ParseAddressOrWildcard(const json_spirit::Value& value)
{
    if (value.get_str() == "*") {
        return "*";
    }
    return ParseAddress(value);
}
```

**Comment by zathras-crypto** [comment] 2015-08-31 22:36
Confirmed behaviour also, nice catch!!!

@dexX7 yep that sounds like a plan, it's not feasible to just allow wildcards in ```ParseAddress``` since there are many places where a wildcard is not supported (such as a from address), so your approach sounds like the simplest way to handle it as we can be granular about whether we support a wildcard in the field :)

**Comment by dexX7** [comment] 2015-08-31 23:01
Fix pending via #213.

@achamely: after #213 I'd like to merge #207, which triggers a reparse (thanks to @zathras-crypto .. :). This should take about 10-25 minutes, but I just wanted to give you a heads up.

**Comment by achamely** [comment] 2015-09-01 01:19
Sweet, thanks guys. will check tomorrow after 213 gets merged (and noted on the 207 reparse)

**Closed** 2015-09-01 13:28 UTC
Labels: api, bug

**Comment by dexX7** [comment] 2015-09-01 13:30
@achamely: fix merged. :)

**Comment by achamely** [comment] 2015-09-01 17:25
thanks guys, i'm pulling / compiling now. will report back

**Comment by achamely** [comment] 2015-09-01 20:34
Confirmed fixed and functional.  Thanks guys.  
@dexX7 the reparse took a bit longer than 25 min fyi (closer to 2 hours) but that's probably due to the machine i'm working on

**Comment by dexX7** [comment] 2015-09-01 20:47
2 hours? Wow, that's a lot. Did you reparse recently, but before we added the block skipping and checkpointing? For me this cut the time in half, so I don't even want to imagine, hehe.. :)

**Comment by zathras-crypto** [comment] 2015-09-02 08:35
> (closer to 2 hours)

Wow, even with slow hardware the seed blocks should make it quicker than that - do you perhaps run with ```--omnidebug=all```?

**Comment by achamely** [comment] 2015-09-02 13:34
yes there had a been a fresh reparse a about a week ago and no, it wasn't running with omnidebug
at the time

**Comment by zathras-crypto** [comment] 2015-09-03 00:33
For comparison on fairly underwhelming hardware a fresh parse for me is somewhere between 5 and 8 minutes depending on OS caching.  2 hours sounds like either blisteringly slow hardware or something is wrong :(
