### ISSUE TITLE
SENT USDT TO TETHER US #31 BY MISTAKE

### ISSUE THREAD

**Issue by 721121** [OmniLayer/omnicore#558] opened 2018-02-22 09:40 UTC
PLEASE how can I access my money that I send and arrive at your address by mistake
reference>8ee25b9c30d67279c77ece638732a39daa75980ee20c72408ddf21709b434bfc
Record
DepositsReturn Export the complete history of withdrawals
State CurrencyQuantity Date Information
Completed USDT258.16657335 2018-02-18 07:08:15
Address: 1uXSDsn7wLHcFxPgB9w434nzxDz2fi2Tb
Txid: 8ee25b9c30d67279c77ece638732a39daa75980ee20c72408ddf21709b434bfc
1uXSDsn7wLHcFxPgB9w434nzxDz2fi2Tb
This address was first seen 2/18/2018 3:50:32 PM
Balances
ID Name Reserved Balance Available Balance

Bitcoin - 0.00000546
1 Omni 0 0
31 TetherUS 0.00 258.16657335

**Comment by dexX7** [comment] 2018-02-22 10:06
This is a duplicate of #557.

**Closed by dexX7** 2018-02-22 10:06 UTC
