### ISSUE TITLE
selected inputs for the send transaction

### ISSUE THREAD

**Issue by macrotea** [OmniLayer/omnicore#608] opened 2018-05-11 15:08 UTC
Hello, I also have the same problem.

Omni_send 1h4f8BfWBmZoDDmtLXdPcs3DbkRpbFYjG 1F3kKH4buPodMK49Rm1QcAracQSbsusx4e 310.1

Remind me:

Error with selected inputs for the send transaction (code -206)

But I pass the tx:

The account corresponding to 1h4f8BfWBmZoDDmtLXdPcs3DbkRpbFYjG is:

349e5568-4f18-462e-8581-08fec1974881

The account corresponding to 1F3kKH4buPodMK49Rm1QcAracQSbsusx4e is:

C8b0145a-0a90-4143-bfc8-a7e6ae54744f

However, when I check the BTC balance of the two account,

349e5568-4f18-462e-8581-08fec1974881

**Btc:0.00101638**

C8b0145a-0a90-4143-bfc8-a7e6ae54744f

**Btc:0**

therefore

1h4f8BfWBmZoDDmtLXdPcs3DbkRpbFYjG should have enough BTC to send this usdt transaction.

But why is it a failure? Consult! Thanks!!!

**Comment by dexX7** [comment] 2018-05-15 11:15
Duplicate of #609.

**Closed by dexX7** 2018-05-15 11:15 UTC
