### ISSUE TITLE
Launch and immediate quit crashes "OmniCore-Qt quit unexpectedly" on Mac OS X.

### ISSUE THREAD

**Issue by msgilligan** [OmniLayer/omnicore#298] opened 2015-12-02 04:19 UTC
To reproduce:
1. Launch OmniCore-Qt by double-clicking
2. As soon as the start screen with the 'Verifying Blocks' message appears, type Command-Q (quit)
3. It will take a while before the quit command is received and acted upon, but when it is the app crashes.

Attached is the crash log.

[MacOSCrash.txt](https://github.com/OmniLayer/omnicore/files/49376/MacOSCrash.txt)

**Comment by dexX7** [comment] 2015-12-02 12:13
After step 2, I assume there is a new window, indicating a shutdown?

My guess right now is that this is an upstream issue, because the Omni parts are not yet initialized at this stage. Nevertheless, we should take a look at this.

Could you please try to add `debug=1` and `omnidebug=all` to your `bitcoin.conf`, then try again and paste the last lines of the `debug.log` and `omnicore.log` (if there is any content)?

**Comment by dexX7** [comment] 2015-12-02 13:00
Also, are you able to reproduce the issue with a stock Bitcoin Core 0.10.4 build?

Here are the binaries for 0.10.4-rc1 (which was then released as release): https://bitcoin.org/bin/bitcoin-core-0.10.4/test/

**Comment by msgilligan** [comment] 2015-12-03 00:42
> After step 2, I assume there is a new window, indicating a shutdown?

Yes.

> Also, are you able to reproduce the issue with a stock Bitcoin Core 0.10.4 build?

I have stock Bitcoin Core Qt 10.2 and *yes* it crashes, too.

**Comment by dexX7** [comment] 2015-12-03 12:42
I created an upstream issue. It would be nice, if you could try it with Bitcoin Core 0.11 (or master) as well, and attach the `debug.log`.

**Comment by msgilligan** [comment] 2015-12-03 19:56
No problem switching back and forth between Bitcoin Core Qt 0.11 and Omni Core Qt 0.0.10RC3?

**Comment by dexX7** [comment] 2015-12-04 12:24
> No problem switching back and forth between Bitcoin Core Qt 0.11 and Omni Core Qt 0.0.10RC3?

Yes, this isn't a problem and switching back and forth is supported.

**Comment by dexX7** [comment] 2017-07-04 06:58
Looks like this was resolved https://github.com/bitcoin/bitcoin/issues/7163#issuecomment-259925664.

**Closed by dexX7** 2017-07-04 06:58 UTC
Labels: bug
